openapi: 3.0.0
info:
  title: ODL-Info API
  description: Daten zur radioaktiven Belastung in Deutschland
  version: 0.0.1
servers:
  - url: https://odlinfo.bfs.de/daten
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
      description: Aktuell werden Zugangsdaten benötigt, die per Mail an ePost@bfs.de erfragt werden können. Die Barriere ist temporär und soll bald entfernt werden (siehe https://twitter.com/strahlenschutz/status/1429750786590916608).
  schemas:
    Statistics:
      type: object
      properties:
        betriebsbereit:
          type: number
          example: 1728
          description: Anzahl betriebsbereiter Messstationen
        mwavg:
          type: object
          properties:
            mw:
              type: number
              example: 0.090
              description: Tagesmittelwert aller Stationen
            t:
              type: string
              description: Zeitstempel Tag
        mwmin:
          type: object
          properties:
            mw:
              type: number
              example: 0.090
              description: Tagesmittelwert
            kenn:
              type: string
              example: '010020002'
              description: Kennnummer der Station mit dem kleinsten Tagesmittelwert
        mwmax:
          type: object
          properties:
            mw:
              type: number
              example: 0.090
              description: Tagesmittelwert
            kenn:
              type: string
              example: '010020002'
              description: Kennnummer der Station mit dem höchsten Tagesmittelwert
    BasicTimeSeries:
      type: object
      description: Grundlegende Zeitreihe (Zeitstempel und Strahlungsmesswerte).
      properties:
        t:
          type: array
          description: UTC-Zeitstempel der Messwerte
          items:
            type: string
        mw:
          type: array
          description: Messwerte in µSv/h
          items:
            type: number
    ExtendedTimeSeries:
      type: object
      description: Erweiterte Zeitreihe mit Prüfstatus und Niederschlagswahrscheinlichkeiten.
      allOf:
        - $ref: '#/components/schemas/BasicTimeSeries'
      properties:
        ps:
          type: array
          description: Prüfstatus der Messwerte. Ein Status ungleich 0 zeigt einen Messwert an, der auffällig ist und überprüft werden muss
          items:
            type: number
        tr:
          type: array
          description: Zeitstempel zu den Niederschlagswahrscheinlichkeiten
          items:
            type: string
        r:
          type: array
          description: Regenwahrscheinlichkeit
          items:
            type: number
    CosmicTimeSeries:
      type: object
      description: Erweiterte Zeitreihe mit kosmischen Messwerten.
      allOf:
        - $ref: '#/components/schemas/ExtendedTimeSeries'
      properties:
        cos:
          type: array
          description: Kosmischer Anteil des Messwertes in µSv/h
          items:
            type: number
        ter:
          type: array
          description: Terrestrischer Anteil des Messwertes in µSv/h
          items:
            type: number
    Station:
      type: object
      description: Spezifikation einer Messstation.
      properties:
        ort:
          type: string
          example: Saarbrücken-Gersweiler
          description: Ortsname
        kid:
          type: number
          enum: [1, 2, 3, 4, 5, 6]
          example: 4
          description: Messnetzknoten-ID der Station (1 = Freiburg, 2 = Berlin, 3 = München, 4 = Bonn, 5 = Salzgitter, 6 = Rendsburg)
        imis:
          type: string
          example: Z1877
          description: IMIS-ID
        status:
          type: number
          example: 1
          enum: [0, 1, 128, 2048]
          description: Zustand der Station (0 = defekt, 1 = in Betrieb, 128 = Testbetrieb, 2048 = Wartung)
        hoehe:
          type: number
          example: 240
          description: Höhe der Station über NN
        lon:
          type: number
          example: 6.93
          description: Längengrad
        mw:
          type: number
          example: 0.104
          description: Aktueller Messwert in µSv/h
        lat:
          type: number
          example: 49.24
          description: Breitengrad
        plz:
          type: string
          example: '66128'
          description: PLZ

security:
  - basicAuth: []
      
paths:
  /json/stat.json:
    get:
      summary: Statistiken zu den Messstationen.
      responses:
        '200':
          description: Erfolgreicher Abruf
          content:
            application/json:
              example:
                betriebsbereit: 1728
                mwavg:
                  mw: 0.09
                  t: '2016-04-04'
                mwmax:
                  mw: 0.178
                  kenn: '083370490'
                mwmin:
                  mw: 0.042
                  kenn: '010020002'
              schema:
                $ref: '#/components/schemas/Statistics'
                  
                      
  /json/stamm.json:
    get:
      summary: Liste aller verfügbaren Messstationen.
      responses:
        '200':
          description: JSON-Objekt der verfügbaren Messstationen
          content:
            application/json:
              example:
                '100411002':
                  ort: Saarbrücken-Gersweiler
                  kid: 4
                  imis: Z1877
                  status: 1
                  hoehe: 240
                  lon: 6.93
                  mw: 0.104
                  lat: 49.24
                  plz: '66128'
              schema: 
                type: object
                properties:
                  /^[0-9]{9}$/:
                    $ref: '#/components/schemas/Station'
  
  /json/{id}.json:
    get:
      summary: Stammdaten und Zeitreihen zu einer bestimmten Messstation.
      parameters:
      - in: path
        name: id
        schema:
          type: integer
          example: 097741851
        required: true
        description: ID der Messstation
      responses:
        '200':
          description: Erfolgreicher Abruf
          content:
            application/json:
              example:
                stamm:
                  ort: Achern OT Gamshurst
                  kenn: '083170010'
                  plz: '77855'
                  status: 1
                  kid: 1
                  hoehe: 100
                  lon: 8.02
                  lat: 48.66
                  mw: 0.107
                mw1h:
                  t:
                  - 2021-08-15 00:00
                  - 2021-08-15 01:00
                  mw:
                  - 0.109
                  - 0.308
                  ps:
                  - 0
                  - 2
                  tr:
                  - 2021-08-15 01:00
                  - 2021-08-15 02:00
                  r:
                  - 0
                  - 0.005
                mw24h:
                  t:
                  - '2020-08-21'
                  - '2020-08-22'
                  mw:
                  - 0.111
                  - 0.109
              schema:
                type: object
                properties:
                  stamm:
                    $ref: '#/components/schemas/Station'
                  mw1h:
                    $ref: '#/components/schemas/ExtendedTimeSeries'
                  mw24h:
                    $ref: '#/components/schemas/BasicTimeSeries'

  /json/{id}ct.json:
    get:
      summary: Stammdaten und Zeitreihen zu einer bestimmten Messstation inklusive kosmisch-terrestrischer Daten.
      parameters:
        - in: path
          name: id
          schema:
            type: integer
            example: 097741851
          required: true
          description: ID der Messstation
      responses:
        '200':
          description: Erfolgreicher Abruf
          content:
            application/json:
              example:
                stamm:
                  ort: Achern OT Gamshurst
                  kenn: '083170010'
                  plz: '77855'
                  status: 1
                  kid: 1
                  hoehe: 100
                  lon: 8.02
                  lat: 48.66
                  mw: 0.107
                mw1h:
                  t:
                  - 2021-08-15 00:00
                  - 2021-08-15 01:00
                  mw:
                  - 0.109
                  - 0.308
                  ps:
                  - 0
                  - 2
                  tr:
                  - 2021-08-15 01:00
                  - 2021-08-15 02:00
                  r:
                  - 0
                  - 0.005
                  cos:
                  - 0.041
                  - 0.041
                  ter:
                  - 0.068
                  - 0.067
                mw24h:
                  t:
                  - '2020-08-21'
                  - '2020-08-22'
                  mw:
                  - 0.111
                  - 0.109
                  cos:
                  - 0.041
                  - 0.041
                  ter:
                  - 0.07
                  - 0.068
              schema:
                type: object
                properties:
                  stamm:
                    $ref: '#/components/schemas/Station'
                  mw1h:
                    $ref: '#/components/schemas/CosmicTimeSeries'
                  mw24h:
                    $ref: '#/components/schemas/BasicTimeSeries' 
          
